services:
  backend:
    build:
      context: ./backend
    container_name: online-store-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
    - uploads-data:/app/uploads    

  frontend:
    build:
      context: ./frontend
    container_name: online-store-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80"